version: '3.9'

services:
  db:
    image: postgres:15
    container_name: advweb_db
    environment:
      POSTGRES_DB: advweb
      POSTGRES_USER: advweb_user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - advweb_db_data:/var/lib/postgresql/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: advweb_keycloak
    command: start
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/keystore.p12
      KC_HTTPS_CERTIFICATE_KEY_STORE_PASSWORD: mypass
      KC_HTTPS_CERTIFICATE_KEY_STORE_TYPE: PKCS12
      KC_HTTPS_PORT: 8443
      KC_PROXY: edge
      KC_HOSTNAME: advweb.duckdns.org
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/advweb
      KC_DB_USERNAME: advweb_user
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public
    ports:
      - "8443:8443"
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data
      - /etc/letsencrypt/live/advweb.duckdns.org/keystore.p12:/etc/x509/https/keystore.p12:ro
    restart: always

  app:
    build: .
    container_name: advweb_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/advweb
      SPRING_DATASOURCE_USERNAME: advweb_user
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://advweb.duckdns.org:8443/realms/advweb
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://advweb.duckdns.org:8443/realms/advweb/protocol/openid-connect/certs
    depends_on:
      - db
      - keycloak
    ports:
      - "8081:8080"
    volumes:
      - uploads:/app/uploads
    restart: on-failure

volumes:
  advweb_db_data:
    name: advweb_db_data
  keycloak_data:
    name: advweb_keycloak_data
  uploads:
    name: advweb_uploads