services:
  db:
    image: postgres:15
    container_name: advweb_db
    environment:
      POSTGRES_DB: advweb
      POSTGRES_USER: advweb_user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - advweb_db_data:/var/lib/postgresql/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: advweb_keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_LOG_LEVEL: info
    ports:
      - "8082:8080"
    restart: always

  app:
    build: .
    container_name: advweb_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/advweb
      SPRING_DATASOURCE_USERNAME: advweb_user
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/advweb
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/advweb/protocol/openid-connect/certs
    depends_on:
      - db
      - keycloak
    ports:
      - "8081:8080"
    volumes:
      - uploads:/app/uploads
    restart: on-failure

volumes:
  advweb_db_data:
    name: advweb_db_data
  uploads:
    name: advweb_uploads
