spring.application.name=advweb

spring.datasource.url=jdbc:postgresql://localhost:5432/advweb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/advweb
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/advweb/protocol/openid-connect/certs

spring.data.web.pageable.max-page-size=20

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

feature.security.disabled=false
