spring.application.name=advweb

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/advweb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:advweb_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

app.public.base-url=${APP_PUBLIC_BASE_URL:https://advweb.duckdns.org}
app.keycloak.base-url=${APP_KEYCLOAK_BASE_URL:${app.public.base-url}/auth}
app.keycloak.realm=${APP_KEYCLOAK_REALM:advweb}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${APP_KEYCLOAK_ISSUER_URI:${app.keycloak.base-url}/realms/${app.keycloak.realm}}
server.forward-headers-strategy=framework

spring.data.web.pageable.max-page-size=20

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

springdoc.swagger-ui.oauth.client-id=${SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_ID:advweb-swagger}
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
