spring.application.name=advweb

spring.datasource.url=jdbc:postgresql://db:5432/advweb
spring.datasource.username=advweb_user
spring.datasource.password=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://advweb.duckdns.org/realms/advweb
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://advweb.duckdns.org/realms/advweb/protocol/openid-connect/certs

spring.data.web.pageable.max-page-size=20

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB