apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: advweb-db-data
  namespace: advweb
  name: advweb-db-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
