apiVersion: apps/v1
kind: Deployment
metadata:
  name: advweb-demo
  namespace: advweb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 #don't delete the old pod until the new one is ready
      maxSurge: 1 # create an additional pod while the new pod is starting
  selector:
    matchLabels:
      app: advweb-demo
  template:
    metadata:
      labels:
        app: advweb-demo
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      volumes:
        - name: postgres-data
          hostPath:
            path: /var/lib/docker/volumes/advweb_db_data/_data
            type: DirectoryOrCreate
        - name: uploads-data
          hostPath:
            path: /var/lib/docker/volumes/advweb_uploads/_data
            type: DirectoryOrCreate
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: advweb-env
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: advweb-env
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: advweb-env
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10

        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10

        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          ports:
            - containerPort: 2181
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10

        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://localhost:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 10

        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1
          args:
            - start
            - --http-enabled=true
            - --http-port=8081
            - --proxy-headers=xforwarded
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15

        - name: advweb-app
          image: catwarden09/advweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          envFrom:
            - secretRef:
                name: advweb-env
          env:
            - name: SERVER_PORT
              value: "8088"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/advweb
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_DATA_REDIS_HOST
              value: localhost
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: localhost:9092
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://localhost:8081/auth/realms/advweb/protocol/openid-connect/certs
          volumeMounts:
            - name: uploads-data
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
