apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: advweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      enableServiceLinks: false
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
            - name: zookeeper-log
              mountPath: /var/lib/zookeeper/log
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /var/lib/docker/volumes/advweb_zookeeper_data/_data
            type: DirectoryOrCreate
        - name: zookeeper-log
          hostPath:
            path: /var/lib/docker/volumes/advweb_zookeeper_log/_data
            type: DirectoryOrCreate
