CREATE TABLE advertisements
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id                   BIGINT                                  NOT NULL,
    name                        VARCHAR(255)                            NOT NULL,
    description                 VARCHAR(255)                            NOT NULL,
    price                       DOUBLE PRECISION                        NOT NULL,
    address                     VARCHAR(255),
    category                    VARCHAR(255)                            NOT NULL,
    subcategory                 VARCHAR(255)                            NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE,
    ad_moderation_status        SMALLINT                                NOT NULL,
    moderation_rejection_reason VARCHAR(255),
    CONSTRAINT PK_ADVERTISEMENTS PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_EMAIL UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_PHONE UNIQUE (phone);

ALTER TABLE advertisements
    ADD CONSTRAINT FK_ADVERTISEMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);