CREATE TABLE weekly_digest_log
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    week_key VARCHAR(20)                             NOT NULL,
    sent_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_weekly_digest_log PRIMARY KEY (id),
    CONSTRAINT uc_weekly_digest_log_user_week UNIQUE (user_id, week_key),
    CONSTRAINT fk_weekly_digest_log_user FOREIGN KEY (user_id) REFERENCES users (id)
);
