CREATE TABLE advertisement_categories
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    parent_id BIGINT,
    CONSTRAINT pk_advertisement_categories PRIMARY KEY (id)
);

ALTER TABLE advertisements
    ADD category_id BIGINT;

ALTER TABLE advertisements
    ADD subcategory_id BIGINT;

ALTER TABLE advertisements
    ALTER COLUMN category_id SET NOT NULL;

ALTER TABLE advertisements
    ALTER COLUMN subcategory_id SET NOT NULL;

ALTER TABLE advertisements
    ADD CONSTRAINT FK_ADVERTISEMENTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES advertisement_categories (id);

ALTER TABLE advertisements
    ADD CONSTRAINT FK_ADVERTISEMENTS_ON_SUBCATEGORY FOREIGN KEY (subcategory_id) REFERENCES advertisement_categories (id);

ALTER TABLE advertisement_categories
    ADD CONSTRAINT FK_ADVERTISEMENT_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES advertisement_categories (id);

ALTER TABLE advertisements
    DROP COLUMN category;

ALTER TABLE advertisements
    DROP COLUMN subcategory;