CREATE TABLE images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url          VARCHAR(255)                            NOT NULL,
    linked_to_ad BOOLEAN,
    ad_id        BIGINT,
    CONSTRAINT PK_IMAGES PRIMARY KEY (id)
);