CREATE TABLE reviews
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text                        VARCHAR(255)                            NOT NULL,
    rating                      INTEGER                                 NOT NULL,
    moderation_status           SMALLINT                                NOT NULL,
    moderation_rejection_reason VARCHAR(255),
    author_id                   BIGINT                                  NOT NULL,
    recipient_id                BIGINT                                  NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT UC_REVIEWS_ON_AUTHOR_ID_RECIPIENT_ID UNIQUE (author_id, recipient_id);