CREATE TABLE avatars
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path           VARCHAR(255)                            NOT NULL,
    url            VARCHAR(255)                            NOT NULL,
    linked_to_user BOOLEAN,
    user_id        BIGINT,
    CONSTRAINT pk_avatars PRIMARY KEY (id)
);

ALTER TABLE avatars
    ADD CONSTRAINT uc_avatars_path UNIQUE (path);

ALTER TABLE avatars
    ADD CONSTRAINT uc_avatars_url UNIQUE (url);